version: "3.9"
services:
  pipeline:
    build:
      context: .
      dockerfile: docker/pipeline.Dockerfile
    restart: unless-stopped
    environment:
      - TRUSTED_SOC_DATA_DIR=/app/data
    volumes:
      - ./data:/app/data
  dashboard:
    build:
      context: .
      dockerfile: docker/dashboard.Dockerfile
    restart: unless-stopped
    depends_on:
      - pipeline
    environment:
      - TRUSTED_SOC_DATA_DIR=/app/data
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
  wazuh:
    image: wazuh/wazuh-oss:4.6.0
    restart: unless-stopped
    ports:
      - "1514:1514/udp"
      - "1515:1515"
      - "55000:55000"
    environment:
      - WAZUH_PASSWORD=SecretPassword1!
    volumes:
      - wazuh_data:/var/ossec/data
  wazuh-dashboard:
    image: wazuh/wazuh-dashboard:4.6.0
    restart: unless-stopped
    depends_on:
      - wazuh
    environment:
      - WAZUH_API_URL=https://wazuh:55000
      - DASHBOARD_USERNAME=admin
      - DASHBOARD_PASSWORD=SecretPassword1!
      - WAZUH_API_USER=admin
      - WAZUH_API_PASSWORD=SecretPassword1!
    ports:
      - "5601:5601"
    volumes:
      - wazuh_dashboard_data:/usr/share/wazuh-dashboard/data
volumes:
  wazuh_data:
  wazuh_dashboard_data:
